[env]
dev_hostname = "internet.com"
dev_showBetaBadge = "true"
dev_onlyBetaUsers = "true"

[[mounts]]
source = "templates/environment.json"
destination = "out/environment.json"
processor = "handlebars"

[[mounts]]
source = "templates/environment.json"
destination = "out/environment.tera.json"
processor = "tera"

[[mounts]]
source = "templates/environment.json"
destination = "out/environment.orig.json"
processor = "copy"