name: npm-release

on:
  push:
    tags: ['*.*.*']

jobs:
  wasm-rel:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run tests
      run: cargo test --verbose

    - name: Install dependencies
      run: |
        rustup target add wasm32-unknown-unknown
        mkdir dist
        mkdir builds
    - name: Build WASM32
      run: ./build.sh
    - name: Node setup
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
        # Defaults to the user or organization that owns the workflow file
        scope: '@octocat'
    - name: Yarn build
      working-directory: ./nodejs
      run: yarn --frozen-lockfile
    - name: Yarn release
      working-directory: ./nodejs
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
